server:
  image: nginx
  restart: always
  ports:
    - 80:80
    - 443:443
  restart: always
  volumes:
    - ./nginx/conf/:/etc/nginx/conf.d/:ro
    - ./certbot/www/:/var/www/certbot/:ro
  links:
    - web:web
certbot:
  image: certbot/certbot:latest
  volumes:
    - ./certbot/www/:/var/www/certbot/:rw
    - ./certbot/conf/:/etc/letsencrypt/:rw
web:
  extends:
    file: docker-compose.base.yml
    service: web
  expose:
    - "5000"
  command: gunicorn app:app -b :5000 --name app --log-level=debug --log-file=-
